### ISSUE TITLE
List of processes running on AIX

### ISSUE THREAD

**Issue by acdmail** [thorhs/node_exporter_aix#14]
hi,
Could you advise please if there is any chance that list of processes running on aix will be added to metrics returned by exporter?

Thanks
Oleg

**Comment by thorhs** [comment]
I have no plans at this stage to add them myself, but would be open to pull requests if anyone wants to add them.

I'm personally not fond of data with low cardinality labels being ingested into the prometheus instances I'm running, but I would not stand in the way of others doing that.
